export const UPDATE_EDITOR_TEXT = 'UPDATE_EDITOR_TEXT';
export const SET_COMMAND_MODE = 'SET_COMMAND_MODE';
export const SET_SELECTED_TEXT = 'SET_SELECTED_TEXT';
export const SET_SELECTED_SYNONYM = 'SET_SELECTED_SYNONYM';
export const SET_SYNONYMS = 'SET_SYNONYMS';
export const SET_EDITOR_TEXT_COLOR = 'SET_EDITOR_TEXT_COLOR';
